import { chromium, type BrowserContext, type Locator, type Page } from "playwright";
import fs from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(process.cwd(), "tools/gemini-web-agent");
const PROFILE_DIR = path.join(ROOT, "chrome-profile");
const OUTPUT_DIR = path.join(ROOT, "output");
const QUEUE_PATH = path.join(ROOT, "queue.json");
const APPROVAL_PATH = path.join(ROOT, "approval-queue.json");
const LOG_PATH = path.join(PROFILE_DIR, "generation-log.json");
const GEMINI_URL = "https://gemini.google.com/app";
const FIVE_MINUTES = 5 * 60 * 1000;
const HOUR = 60 * 60 * 1000;
const MAX_PER_HOUR = 12;
const POLL_MS = 10_000;
const MAX_ATTEMPTS = 4;

const QA_PROMPT = `You are the strict DMH internal image QA gate. Analyze the immediately preceding generated hairstyle image against the requested hairstyle prompt and DMH identity-preservation rules. Return ONLY valid JSON: {"overall":0,"identity":0,"hairOnly":"PASS|FAIL","styleAccuracy":0,"rootIntegration":0,"lightingConsistency":0,"artifacts":"NONE|FOUND","verdict":"APPROVE|REGENERATE","reason":"short factual reason","refinement":"one targeted correction only, or empty string"}. Score 0-10. APPROVE requires overall >= 9.5, identity >= 9.5, styleAccuracy >= 9.5, rootIntegration >= 9.5, lightingConsistency >= 9.5, hairOnly PASS, artifacts NONE. If any hard gate fails, verdict must be REGENERATE. Refinement must address only the most important failure and preserve all passing requirements.`;

type JobStatus = "QUEUED" | "PROCESSING" | "WAITING_QA" | "REVIEW" | "APPROVED" | "REJECTED" | "FAILED";
type Job = { id: string; imagePath: string; prompt: string; styleKey?: string; status?: JobStatus; attempts?: number; lastError?: string; updatedAt?: string };
type QA = { overall: number; identity: number; hairOnly: "PASS" | "FAIL"; styleAccuracy: number; rootIntegration: number; lightingConsistency: number; artifacts: "NONE" | "FOUND"; verdict: "APPROVE" | "REGENERATE"; reason: string; refinement: string };

async function pause(ms: number, reason: string) { console.log(`${reason} (${Math.ceil(ms / 1000)}s)...`); await new Promise(r => setTimeout(r, ms)); }
async function readJson<T>(file: string, fallback: T): Promise<T> { try { return JSON.parse(await fs.readFile(file, "utf8")) as T; } catch { return fallback; } }
async function writeJson(file: string, value: unknown) { await fs.writeFile(file, JSON.stringify(value, null, 2), "utf8"); }
async function queue(): Promise<Job[]> { return readJson<Job[]>(QUEUE_PATH, []); }
async function saveQueue(value: Job[]) { await writeJson(QUEUE_PATH, value); }
async function approvalQueue(): Promise<Job[]> { return readJson<Job[]>(APPROVAL_PATH, []); }
async function generationLog(): Promise<number[]> { return readJson<number[]>(LOG_PATH, []); }
async function recordGeneration() { const now = Date.now(); const recent = (await generationLog()).filter(t => now - t < HOUR); recent.push(now); await writeJson(LOG_PATH, recent); console.log(`Gemini generation ${recent.length}/${MAX_PER_HOUR} in rolling hour.`); }
async function waitSlot() { while (true) { const now = Date.now(); const recent = (await generationLog()).filter(t => now - t < HOUR); await writeJson(LOG_PATH, recent); if (recent.length >= MAX_PER_HOUR) { await pause(Math.max(1000, HOUR - (now - recent[0]) + 1000), "Hourly Gemini cap reached"); continue; } const last = recent.at(-1); if (last !== undefined && now - last < FIVE_MINUTES) { await pause(FIVE_MINUTES - (now - last), "Waiting for five-minute Gemini slot"); continue; } return; } }
async function firstVisible(locators: Locator[]): Promise<Locator> { for (const l of locators) { try { for (let i = await l.count() - 1; i >= 0; i--) { const x = l.nth(i); if (await x.isVisible()) return x; } } catch {} } throw new Error("Required Gemini control not found"); }
async function upload(page: Page, file: string) { const input = page.locator('input[type="file"]'); if (await input.count()) { await input.first().setInputFiles(file); await pause(2500, "Reference uploaded"); return; } const add = await firstVisible([page.getByRole("button", { name: /open upload file menu|add files|attach files|upload files/i }), page.locator('button[aria-label*="Upload" i]'), page.locator('button[aria-label*="Attach" i]')]); const chooser = page.waitForEvent("filechooser", { timeout: 10000 }).catch(() => null); await add.click(); const c = await chooser; if (c) { await c.setFiles(file); await pause(2500, "Reference uploaded"); return; } const fallback = page.locator('input[type="file"]'); if (await fallback.count()) { await fallback.first().setInputFiles(file); await pause(2500, "Reference uploaded"); return; } throw new Error("Gemini file upload control unavailable"); }
async function composer(page: Page): Promise<Locator> { return firstVisible([page.locator('textarea'), page.locator('[contenteditable="true"][role="textbox"]'), page.locator('[contenteditable="true"]')]); }
async function send(page: Page, text: string) { const box = await composer(page); await pause(900, "Preparing Gemini prompt"); await box.fill(text); await pause(700, "Prompt entered"); for (const l of [page.getByRole("button", { name: /send|submit/i }), page.locator('button[aria-label*="Send" i]')]) { try { const b = await firstVisible([l]); await b.click(); return; } catch {} } await box.press("Enter"); }
async function largeImages(page: Page) { return page.evaluate(() => Array.from(document.images).map(i => ({ src: i.currentSrc || i.src, area: i.naturalWidth * i.naturalHeight })).filter(x => x.src && x.area >= 512 * 512).sort((a,b) => b.area-a.area).map(x => x.src)); }
async function waitImage(page: Page, before: Set<string>) { await pause(3500, "Gemini is processing"); const end = Date.now() + 180000; while (Date.now() < end) { const now = await largeImages(page); if (now.some(s => !before.has(s))) return; await page.waitForTimeout(1000); } throw new Error("Timed out waiting for Gemini image"); }
async function capture(page: Page, before: Set<string>, output: string) { const source = (await largeImages(page)).find(s => !before.has(s)); if (!source) throw new Error("Generated image asset not found"); if (source.startsWith("data:")) { const b = source.split(",",2)[1]; if (!b) throw new Error("Invalid data image"); await fs.writeFile(output, Buffer.from(b,"base64")); return; } if (source.startsWith("blob:")) { const b = await page.evaluate(async url => { const r=await fetch(url); const blob=await r.blob(); return await new Promise<string>((resolve,reject)=>{const fr=new FileReader(); fr.onloadend=()=>{const x=String(fr.result); const i=x.indexOf(","); i<0?reject(new Error("Invalid blob")):resolve(x.slice(i+1));}; fr.onerror=()=>reject(fr.error); fr.readAsDataURL(blob);}); }, source); await fs.writeFile(output, Buffer.from(b,"base64")); return; } const r=await page.request.get(source); if(!r.ok()) throw new Error(`Image download failed: HTTP ${r.status()}`); await fs.writeFile(output, await r.body()); }
async function qa(page: Page, prompt: string): Promise<QA> { const before = await page.locator("body").innerText(); await send(page, QA_PROMPT + "\n\nREQUESTED STYLE PROMPT:\n" + prompt); const end=Date.now()+120000; while(Date.now()<end){ await page.waitForTimeout(1500); const body=await page.locator("body").innerText().catch(()=>""); const tail=body.slice(Math.max(0,before.length-100),body.length); for(const m of tail.matchAll(/\{[\s\S]*?\}/g)){ try{const x=JSON.parse(m[0]) as QA; if(typeof x.overall==="number" && typeof x.verdict==="string") return x;}catch{} } } throw new Error("Timed out waiting for automated QA"); }
async function freshChat(page: Page) { try { const b=await firstVisible([page.getByRole("button", {name:/new chat|new conversation/i}), page.locator('[aria-label*="New chat" i]')]); await b.click(); await page.waitForTimeout(1500); } catch { await page.goto(GEMINI_URL,{waitUntil:"domcontentloaded",timeout:60000}); await page.waitForTimeout(2000); } }
async function waitSignIn(page: Page) { const s=page.getByRole("link",{name:/sign in/i}).or(page.getByRole("button",{name:/sign in/i})); if(await s.count() && await s.first().isVisible().catch(()=>false)){ console.log("Complete Gemini sign-in in the normal Chrome profile."); await page.waitForFunction(()=>Boolean(document.querySelector('textarea,[contenteditable="true"]')),{timeout:600000,polling:1000}); } }
async function processJob(page: Page, job: Job): Promise<void> { job.status="PROCESSING"; job.attempts=(job.attempts??0)+1; job.updatedAt=new Date().toISOString(); await saveQueue(await queue()); await waitSlot(); await freshChat(page); await upload(page,path.resolve(job.imagePath)); const before=new Set(await largeImages(page)); await send(page,job.prompt); await recordGeneration(); await waitImage(page,before); const stamp=new Date().toISOString().replace(/[:.]/g,"-"); const output=path.join(OUTPUT_DIR,`${job.id}-${stamp}.png`); await capture(page,before,output); const result=await qa(page,job.prompt); await writeJson(output.replace(/\.png$/,".qa.json"),{job,result,prompt:job.prompt,checkedAt:new Date().toISOString()}); const hard=result.overall>=9.5&&result.identity>=9.5&&result.styleAccuracy>=9.5&&result.rootIntegration>=9.5&&result.lightingConsistency>=9.5&&result.hairOnly==="PASS"&&result.artifacts==="NONE"; if(result.verdict==="APPROVE"&&hard){ const approvals=await approvalQueue(); approvals.push({...job,status:"REVIEW",outputPath:output,qa:result}); await writeJson(APPROVAL_PATH,approvals); job.status="REVIEW"; console.log(`JOB ${job.id}: QA ${result.overall}/10 -> HUMAN APPROVAL QUEUE`); return; } if(job.attempts>=MAX_ATTEMPTS || !result.refinement){ job.status="FAILED"; job.lastError=`QA failed: ${result.reason}`; console.log(`JOB ${job.id}: failed after ${job.attempts} attempt(s): ${result.reason}`); return; } job.status="QUEUED"; job.prompt=job.prompt+"\n\nTARGETED REFINEMENT — change only this observed defect; preserve all passing requirements:\n"+result.refinement; console.log(`JOB ${job.id}: QA ${result.overall}/10 -> targeted refinement queued`); }
async function main(){ await fs.mkdir(PROFILE_DIR,{recursive:true}); await fs.mkdir(OUTPUT_DIR,{recursive:true}); const browserPath=process.env.CHROME_PATH||"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"; const context:BrowserContext=await chromium.launchPersistentContext(PROFILE_DIR,{executablePath:browserPath,headless:false,acceptDownloads:true,viewport:{width:1440,height:1000}}); const page=context.pages()[0]??await context.newPage(); try{await page.goto(GEMINI_URL,{waitUntil:"domcontentloaded",timeout:60000}); await page.waitForTimeout(2000); await waitSignIn(page); console.log("DMH Gemini R&D worker running. Add jobs to tools/gemini-web-agent/queue.json."); while(true){ const jobs=await queue(); const job=jobs.find(j=>j.status==="QUEUED"||j.status===undefined); if(!job){ await pause(POLL_MS,"R&D queue empty; waiting for new jobs"); continue; } try{await processJob(page,job);}catch(e){job.status="FAILED";job.lastError=e instanceof Error?e.message:String(e);job.updatedAt=new Date().toISOString();console.error(`JOB ${job.id} error: ${job.lastError}`);} await saveQueue(jobs); } } catch(e){console.error(e instanceof Error?e.message:e);console.error("Chrome remains open for inspection.");process.exitCode=1;} }
main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
