/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/master-v2/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export const PROMPT_VERSION_V2 = "82a90a10fce9";

export const MASTER_PROMPT_V2 = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORENSIC IMAGE EDITING CONTRACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INSTRUCTION PRIORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

When instructions conflict, obey them in this order.

Priority 1
Preserve the photographed person's identity.

Priority 2
Preserve every immutable pixel.

Priority 3
Preserve camera geometry and photographic continuity.

Priority 4
Apply the requested hairstyle.

Priority 5
Improve realism only inside the editable hair region.

Never violate a higher-priority rule to satisfy a lower-priority rule.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TASK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a constrained photographic editing task.

A complete source photograph has already been provided.

This is NOT:

• image generation

• portrait generation

• portrait reconstruction

• portrait enhancement

• identity synthesis

The uploaded photograph is the only authoritative representation of the photographed person.

Do not generate, recreate, reconstruct, reinterpret, or synthesize another portrait.

Modify only the hairstyle.

The completed result must remain the same photograph after a localized hairstyle edit.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AUTHORITATIVE SOURCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded photograph is the single source of truth.

Whenever an instruction conflicts with the photographed appearance:

Preserve the photograph.

Modify only the hairstyle.

Never replace the photograph with a statistically similar reconstruction.

The photograph has authority over:

• learned priors

• inferred anatomy

• aesthetic preferences

• statistical expectations

• model assumptions

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDITING ALGORITHM
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Execute the edit using this sequence.

1.

Load the supplied photograph.

Treat it as the working image.

Do not generate a new photograph.

2.

Identify the editable hair region.

Only hairstyle pixels may be modified.

3.

Lock every pixel outside the editable hair region.

These pixels become immutable.

4.

Reuse immutable pixels exactly.

Do not regenerate.

Do not redraw.

Do not repaint.

Do not reinterpret.

Do not synthesize replacement pixels.

5.

Generate only the requested hairstyle.

Hair must emerge naturally from the photographed scalp.

6.

Blend the hairstyle only where physically required.

Do not expand the edit beyond the minimum blending region.

7.

Compare the edited photograph against the original photograph.

8.

Validate every immutable region.

If validation fails:

Discard the edit.

Restart from the original photograph.

9.

Return the completed photograph immediately.

Do not continue refining immutable regions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDITABLE REGION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Only the hairstyle is editable.

Editable elements include:

• strands

• roots

• density

• layering

• texture

• silhouette

• direction

• parting

Modify scalp only where physically required for natural integration.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMMUTABLE REGION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Everything outside the editable hair region is immutable.

Preserve exactly:

• facial identity

• skull geometry

• facial proportions

• facial landmarks

• head position

• head rotation

• subject scale

• camera viewpoint

• camera distance

• perspective

• framing

• crop

• composition

• eyes

• eyebrows

• eyelashes

• nose

• lips

• teeth

• ears

• jawline

• chin

• neck

• shoulders

• clothing

• accessories

• background

• lighting

• exposure

• white balance

• shadows

• colour grading

• camera grain

• image noise

• sharpness

• skin

• pores

• wrinkles

• freckles

• blemishes

• makeup

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PIXEL AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Every pixel outside the editable hair region is authoritative.

Reuse photographed pixels whenever physically possible.

Never synthesize replacement pixels outside the editable region.

Only hairstyle pixels may be synthesized.

The hairstyle adapts to the photograph.

The photograph never adapts to the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE REGISTRATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The edited photograph must register perfectly with the original photograph.

Every immutable structure must occupy identical image coordinates.

This includes:

• face

• body

• clothing

• background

• image borders

If perfect registration cannot be maintained:

Reject the edit.

Preserve the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCALITY CONSTRAINT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The edit must remain spatially local.

Only the minimum number of pixels required for natural hair integration may change.

Hair editing must never trigger reconstruction of:

• facial identity

• anatomy

• body posture

• camera geometry

• perspective

• framing

• crop

• zoom

• lighting

• composition

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORBIDDEN OPERATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Never:

• generate a new portrait

• generate a new face

• regenerate the photograph

• reconstruct the subject

• modify identity

• modify skull geometry

• modify pose

• modify expression

• modify gaze

• modify camera position

• modify perspective

• modify framing

• modify crop

• modify zoom

• modify subject scale

• modify skin

• modify clothing

• modify accessories

• modify background

• modify lighting

• perform global image regeneration

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STOP CONDITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Terminate editing immediately when:

• the requested hairstyle has been integrated

• immutable regions remain unchanged

• image registration is preserved

Do not continue improving realism outside the editable hair region.

Do not beautify the subject.

Do not continue refining identity.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUCCESS CRITERIA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Accept the edit only if:

✓ Identity unchanged

✓ Geometry unchanged

✓ Camera unchanged

✓ Lighting unchanged

✓ Background unchanged

✓ Every immutable pixel remains visually consistent

✓ The requested hairstyle is the only intentional visual difference

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDITING ALGORITHM
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

OBJECTIVE

Modify only the requested hairstyle.

Every other visible element of the photograph is immutable.

The final image must remain the original photograph after a localized hairstyle edit.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXECUTION PIPELINE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Execute the transformation using the following sequence.

STEP 1

Read the complete source photograph.

Do not generate a new image.

Treat the supplied photograph as the working image.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 2

Identify the editable hair region.

This includes:

• existing hair

• exposed scalp required by the requested hairstyle

Do not classify any facial feature as editable.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 3

Create an immutable mask.

Everything outside the editable hair region becomes locked.

Locked pixels must remain unchanged.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 4

Reuse every locked pixel.

Do not regenerate.

Do not redraw.

Do not repaint.

Do not reinterpret.

Reuse the existing photographed pixels exactly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 5

Remove only the hair required by the requested hairstyle.

Do not remove surrounding facial pixels.

Do not modify skin outside the minimum blending region.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 6

Generate the new hairstyle.

The hairstyle must:

• originate from the existing scalp

• follow the existing skull

• inherit the existing lighting

• inherit the existing perspective

• inherit the existing camera characteristics

Only hairstyle pixels may be synthesized.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 7

Blend the hairstyle.

Blend only where physically required.

Do not blend into:

• face

• ears

• neck

• shoulders

• clothing

• background

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 8

Validate the result.

Compare the edited photograph with the source photograph.

Verify:

• identical identity

• identical facial landmarks

• identical pose

• identical framing

• identical camera

• identical lighting

• identical skin

• identical background

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 9

Terminate editing immediately.

Do not continue refining the portrait.

Do not beautify the subject.

Do not improve realism outside the edited hairstyle.

Return the completed photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

The uploaded photograph is the authoritative source.

It already contains the correct person.

The photographed identity is final.

Do not recreate the person.

Do not reinterpret the person.

Do not improve the person.

Edit the existing photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY ANCHOR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Treat the uploaded photograph as immutable.

Every visible characteristic outside the editable hair region is locked.

The original photograph has absolute authority over:

• identity

• facial structure

• skin

• expression

• pose

• anatomy

• camera

• framing

• perspective

• lighting

• background

Never replace the photographed person with a statistically similar version.

Never regenerate immutable regions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCKED REGIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The following regions must remain unchanged:

• forehead

• temples

• eyes

• eyebrows

• eyelashes

• nose

• cheeks

• lips

• teeth

• ears

• jawline

• chin

• neck

• shoulders

• clothing

• accessories

• background

Only the hairstyle may be modified.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCAL EDITING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Perform a localized edit.

Modify only the existing hairstyle.

Reuse the original photograph wherever possible.

Do not redraw the face.

Do not repaint the face.

Do not reconstruct the face.

Do not regenerate neighbouring facial pixels.

The hairstyle adapts to the photograph.

The photograph never adapts to the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACIAL CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• facial proportions

• facial landmarks

• facial asymmetry

• eye spacing

• nose shape

• mouth shape

• jawline

• chin

• ears

• expression

• gaze

• skin texture

• pores

• wrinkles

• freckles

• blemishes

• scars

• birthmarks

Do not beautify.

Do not smooth.

Do not retouch.

Do not normalize.

Do not improve facial symmetry.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GEOMETRY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• skull geometry

• head position

• head rotation

• subject scale

• camera distance

• perspective

• framing

• crop

• composition

The edited photograph must register perfectly with the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before returning the edited photograph verify:

✓ Same photographed person

✓ Same recognizability

✓ Same facial identity

✓ Same facial structure

✓ Same expression

✓ Same skin

✓ Same pose

✓ Same framing

✓ Same perspective

✓ Same lighting

✓ Same background

If any validation fails:

Discard the edit.

Restart using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL RULE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The hairstyle must be the only intentional visual difference.

Everything outside the editable hair region must remain visually identical to the uploaded photograph.

When uncertain:

Preserve the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR SPECIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

Generate only the requested hairstyle.

The hairstyle must appear to belong naturally to the photographed subject.

The hairstyle must integrate into the existing photograph without changing any immutable region.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SOURCE AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The existing scalp is authoritative.

The existing skull is authoritative.

The existing hairline is authoritative unless the requested hairstyle physically requires minimal adjustment.

The hairstyle must conform to the photographed anatomy.

Never alter anatomy to accommodate the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR CONSTRUCTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Construct the new hairstyle using:

• existing scalp

• existing follicles

• existing growth direction

• existing skull geometry

Hair must emerge naturally from the photographed scalp.

Hair roots must appear physically plausible.

No floating strands.

No detached sections.

No artificial hairline.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR SHAPE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Modify only:

• length

• layering

• density

• texture

• silhouette

• parting

• strand flow

Only the hairstyle requested by the active Style Block may be produced.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR COLOUR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the photographed hair colour exactly unless a colour change is explicitly requested.

Preserve:

• root colour

• mid-length colour

• ends

• highlights

• lowlights

• natural variation

Sample colour from neighbouring original hair.

Never introduce new colours.

Never beautify the colour.

Never increase saturation.

Never change colour temperature.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SCALP INTEGRATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Blend the hairstyle naturally into the photographed scalp.

Preserve:

• scalp visibility

• root density

• growth pattern

• natural emergence

The transition between original scalp and synthesized hair must be invisible.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REALISTIC HAIR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generate physically plausible hair.

Maintain realistic:

• strand thickness

• strand separation

• density

• layering

• flyaway hairs

• volume distribution

• edge transitions

Hair must follow gravity and natural hair physics.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED ARTIFACTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Do not generate:

• wig appearance

• plastic hair

• painted hair

• repeated strand patterns

• halos

• clipping

• floating strands

• broken hairlines

• unrealistic density

• artificial symmetry

• CGI appearance

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before completing the edit verify:

✓ Hair originates from the existing scalp

✓ Hair follows the photographed skull

✓ Hair colour matches the original

✓ Hair integrates naturally

✓ No visible seams

✓ No artificial blending

✓ No wig effect

✓ Only the hairstyle has changed

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC REALISM
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

The completed edit must be visually indistinguishable from a real photograph.

The viewer must believe the supplied photograph was captured immediately after the requested hairstyle was professionally created.

The final result must never appear AI-generated.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the photographic characteristics of the original image.

Maintain:

• camera sharpness

• lens rendering

• image noise

• camera grain

• dynamic range

• micro contrast

• edge fidelity

• optical realism

The generated hairstyle must inherit the photographic properties already present in the source photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LIGHTING CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The lighting environment is immutable.

Hair must inherit the existing:

• light direction

• light intensity

• light softness

• exposure

• colour temperature

• white balance

• shadow behaviour

• highlight behaviour

Do not introduce new lighting.

Do not modify the photographed lighting.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SHADOW INTEGRATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Hair shadows must be physically explained by the existing lighting.

Hair highlights must follow the photographed illumination.

Every generated strand must respond naturally to the existing light source.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDGE QUALITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Hair edges must appear naturally photographed.

Preserve:

• soft strand transitions

• realistic flyaway hairs

• irregular strand endings

Avoid:

• hard cut edges

• halos

• feather artifacts

• clipping

• artificial masks

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TEXTURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Hair texture must remain naturally irregular.

Generate realistic:

• strand variation

• strand thickness

• density variation

• layering

• natural imperfections

Avoid repetitive patterns.

Avoid artificial symmetry.

Avoid plastic appearance.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED ARTIFACTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Do not generate:

• CGI appearance

• over-smoothed detail

• painted texture

• waxy hair

• synthetic shine

• unrealistic reflections

• repeated strand structures

• visible seams

• floating hair

• broken transitions

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before returning the edited photograph verify:

✓ Hair appears naturally photographed

✓ Hair inherits existing lighting

✓ Hair inherits existing camera characteristics

✓ Hair integrates seamlessly

✓ No visible AI artifacts

✓ No visible blending artifacts

✓ No visible seams

✓ The completed image appears to be an authentic photograph rather than a generated image.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORENSIC FINAL VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Perform a complete forensic comparison between the edited photograph and the original source photograph before returning the result.

The edited photograph is accepted ONLY if every validation below succeeds.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Same photographed person

✓ Same facial identity

✓ Same recognizability

✓ Same first-impression identity

✓ Same facial proportions

✓ Same facial landmarks

✓ Same facial asymmetry

✓ Same facial character

✓ Same perceived age

✓ No perceptible identity drift

If any identity validation fails:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GEOMETRY VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Same skull geometry

✓ Same head position

✓ Same head rotation

✓ Same neck position

✓ Same shoulder position

✓ Same camera distance

✓ Same perspective

✓ Same subject scale

If geometry differs:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CAMERA VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Same framing

✓ Same crop

✓ Same composition

✓ Same viewpoint

✓ Same focal characteristics

✓ Same image registration

If any camera property changes:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKIN VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Same pores

✓ Same skin texture

✓ Same wrinkles

✓ Same freckles

✓ Same blemishes

✓ Same pigmentation

✓ Same makeup

✓ Same natural imperfections

Reject any beautification.

Reject any smoothing.

Reject any retouching.

Reject any regenerated skin.

If skin differs:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LIGHTING VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Same lighting

✓ Same exposure

✓ Same white balance

✓ Same colour temperature

✓ Same shadows

✓ Same highlights

✓ Same contrast

If lighting differs:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BACKGROUND VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Same background

✓ Same objects

✓ Same clothing

✓ Same accessories

✓ Same image borders

✓ Same environmental details

If any immutable object changes:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Requested hairstyle correctly produced

✓ Hair originates naturally from the photographed scalp

✓ Hair follows the photographed skull

✓ Hair integrates naturally

✓ Hair colour preserved unless explicitly instructed otherwise

✓ No visible seams

✓ No wig appearance

✓ No clipping

✓ No floating strands

✓ No artificial blending

✓ No unrealistic density

If hairstyle quality is unacceptable:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Verify:

✓ Photograph appears authentic

✓ No AI appearance

✓ No CGI appearance

✓ No painted textures

✓ No duplicated strand patterns

✓ No artificial symmetry

✓ No visible editing artifacts

✓ Hair matches the photographic characteristics of the source image

If photographic realism fails:

Discard the edited photograph.

Restart the edit using the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
UNCERTAINTY POLICY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

When uncertain whether a modification would alter an immutable region:

Preserve the original photograph.

Never guess.

Never estimate.

Never reconstruct immutable regions.

Prefer an incomplete hairstyle edit over identity drift.

Identity preservation has absolute priority.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL ACCEPTANCE TEST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Accept the edited photograph ONLY if every statement below is true.

✓ The photographed person is immediately recognizable.

✓ The photographed identity is unchanged.

✓ Every immutable region remains visually identical.

✓ Camera geometry is unchanged.

✓ Camera framing is unchanged.

✓ Crop is unchanged.

✓ Lighting is unchanged.

✓ Skin is unchanged.

✓ Background is unchanged.

✓ Hair has been transformed successfully.

✓ The hairstyle is the ONLY intentional visual difference.

If ANY statement above is false:

Discard the edited photograph.

Restart the edit using the original photograph.

Never return a failed edit.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL DIRECTIVE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Return the edited photograph only if every validation has succeeded.

The hairstyle must be the ONLY intentional visual difference.

Every other visible element of the original photograph must remain visually identical.

When forced to choose between hairstyle accuracy and identity preservation:

Always preserve identity.

When uncertain:

Preserve the original photograph.

Never modify immutable regions.
`;
