/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/master/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export const PROMPT_VERSION = "e6b3bdc53f8c";

export const MASTER_PROMPT = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORENSIC IMAGE EDITING CONTRACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TASK

This is a constrained photographic editing task.

A complete source photograph has already been provided.

The supplied photograph is the authoritative source for the final result.

This is NOT an image generation task.

This is NOT a portrait generation task.

This is NOT a portrait reconstruction task.

This is NOT a portrait enhancement task.

Do not generate a new portrait.

Do not recreate the photographed person.

Do not reinterpret the photographed person.

Do not synthesize an alternative version of the photographed person.

The objective is to perform a localized photographic edit that modifies only the requested hairstyle.

The final image must remain the exact same photograph with only the hairstyle changed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AUTHORITATIVE SOURCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded photograph is the single source of truth.

The original photograph has priority over all learned visual priors.

The original photograph has priority over aesthetic preferences.

The original photograph has priority over statistical expectations.

The original photograph has priority over model assumptions.

If any conflict exists between the requested hairstyle and the supplied photograph,

preserve the photograph,

modify only the hairstyle.

Never replace the original photograph with a visually similar reconstruction.

Never create another version of the person.

Treat the supplied photograph as the master reference throughout the entire editing process.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDITING WORKFLOW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before making any modification:

1. Analyse the complete photograph.

2. Identify the editable hair region.

3. Identify every immutable region.

4. Lock every immutable region.

5. Freeze all immutable pixels.

6. Perform a localized hairstyle edit.

7. Compare the edited photograph against the source photograph.

8. Verify every immutable region remains identical.

Only after every verification step succeeds may the edit be considered complete.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDITABLE REGION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Only the subject's hair system is editable.

This includes:

• Hair strands

• Hair roots

• Hair density

• Hair length

• Hair layering

• Hair direction

• Hair texture

• Hair parting

• Hair silhouette

If the requested hairstyle naturally exposes previously hidden scalp,

only the newly visible scalp required for that hairstyle may also be modified.

Small neighbouring pixels may be adjusted only where physically required for seamless strand integration.

No intentional modification may extend beyond the minimum area required for natural hair integration.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMMUTABLE REGION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Everything outside the editable hair region is immutable.

These regions are authoritative.

They must remain visually identical to the supplied photograph.

This includes:

• Facial identity

• Skull geometry

• Face shape

• Facial proportions

• Facial landmarks

• Head size

• Head position

• Head rotation

• Camera viewpoint

• Camera distance

• Camera perspective

• Camera angle

• Camera height

• Subject scale

• Crop

• Framing

• Composition

• Eyes

• Eyebrows

• Eyelashes

• Nose

• Lips

• Teeth

• Ears

• Jawline

• Chin

• Neck

• Shoulders

• Body posture

• Clothing

• Accessories

• Background

• Lighting

• Shadows

• Exposure

• White balance

• Colour grading

• Camera grain

• Noise

• Sharpness

• Skin

• Skin colour

• Skin texture

• Skin pores

• Freckles

• Wrinkles

• Fine lines

• Makeup

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE REGISTRATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The edited photograph must register perfectly with the supplied photograph.

Outside the editable hair region,

every visible structure must occupy identical image coordinates.

If both photographs are overlaid,

all facial features,

all body features,

all clothing,

all background features,

all image borders,

must align perfectly.

If perfect registration cannot be achieved,

discard the edit.

Preserve the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PIXEL PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Outside the editable hair region,

existing photographic pixels are authoritative.

Do not regenerate them.

Do not redraw them.

Do not repaint them.

Do not reinterpret them.

Do not replace them with visually similar approximations.

Reuse the existing photographic information.

Only pixels belonging to the editable hair region may be synthesized.

The hairstyle must be integrated into the existing photograph.

The photograph must never be regenerated around the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCALITY CONSTRAINT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The edit must remain spatially local.

Modification may propagate only as far as physically required for natural hair integration.

Hair editing must never trigger reconstruction of:

• facial identity

• facial anatomy

• body posture

• camera geometry

• perspective

• framing

• crop

• zoom

• lighting

• composition

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORBIDDEN OPERATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Never:

• generate a new face

• reconstruct facial identity

• reconstruct the portrait

• reconstruct the photograph

• regenerate the subject

• change facial geometry

• change skull geometry

• change head position

• change head rotation

• change camera viewpoint

• change camera distance

• change perspective

• change crop

• change zoom

• change subject scale

• change pose

• change facial expression

• change gaze direction

• change skin appearance

• change skin texture

• change skin tone

• change clothing

• change accessories

• change background

• change lighting

• globally regenerate the image

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STOP CONDITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Editing is complete once:

• the requested hairstyle has been naturally integrated

• every immutable region remains visually identical

• image registration remains perfect

• no further modifications are required

Do not continue improving realism outside the editable hair region.

Do not continue improving identity.

Do not continue refining the portrait.

Stop immediately after the hairstyle has been successfully integrated.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUCCESS CRITERIA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

A successful result appears to be the exact same photograph captured immediately after the subject received a professional haircut.

Identity is unchanged.

Geometry is unchanged.

Pose is unchanged.

Camera is unchanged.

Framing is unchanged.

Lighting is unchanged.

Every non-hair pixel remains visually consistent with the original photograph.

The only intentional visual difference is the requested hairstyle.

MODULE: 05_edit_strategy.md

────────────────────────────────────
EDITING STRATEGY
────────────────────────────────────

This is an image editing task.

It is NOT an image generation task.

An existing real photograph has already been provided.

The photograph already contains the correct:

• subject
• face
• head
• skull
• pose
• camera position
• perspective
• lighting
• expression
• body
• clothing
• background

These elements already exist and must remain the foundation of the final image.

Never replace the photograph with a newly generated portrait.

The final image must remain the original photograph after localized hair editing.

────────────────────────────────────
EDITING PIPELINE
────────────────────────────────────

Perform the transformation using this exact sequence.

Step 1

Read the existing photograph.
Create an immutable mask for every non-hair pixel before editing begins.

Step 2

Identify pixels belonging to existing hair.

Step 3

Preserve every pixel outside the editable hair region.

Step 4

Remove only the hair required for the requested hairstyle.

Step 5

Construct the new hairstyle directly on the existing scalp.

Step 6

Blend the hairstyle naturally into the existing photograph.

Step 7

Stop editing.

Do not regenerate the portrait at any point during this process.

────────────────────────────────────
SOURCE PHOTOGRAPH
────────────────────────────────────

The source photograph is authoritative.

Assume every visible facial feature is already correct.

Assume every visible anatomical measurement is already correct.

Assume every visible proportion is already correct.

Do not improve the subject.

Do not beautify the subject.

Do not reinterpret the subject.

Do not optimize the subject.

The goal is not to create a better portrait.

The goal is to preserve the original portrait while changing only the hairstyle.

────────────────────────────────────
HAIR REPLACEMENT
────────────────────────────────────

Treat the hairstyle as a localized replacement.

The new hairstyle must be attached to the existing scalp.

Hair roots originate from the subject's existing follicles.

Hair follows the existing skull.

Hair follows the existing scalp curvature.

Hair follows the existing head dimensions.

Never create a new skull.

Never create a new forehead.

Never reposition the scalp.

Never reposition the hairline unless explicitly required by the requested hairstyle.

────────────────────────────────────
PIXEL OWNERSHIP
────────────────────────────────────

Every visible pixel belongs to one region.

Region A

Hair

Editable.

Region B

Face

Immutable.

Region C

Neck

Immutable.

Region D

Ears

Immutable.

Region E

Body

Immutable.

Region F

Clothing

Immutable.

Region G

Background

Immutable.

Only Region A may be modified.

No other region may be regenerated.

────────────────────────────────────
LOCALIZED EDITING
────────────────────────────────────

Hair editing must remain spatially localized.

The model must never perform whole-image reconstruction.

The model must never regenerate the complete portrait.

Only replace pixels that are necessary for the hairstyle transformation.

Everything else remains untouched.

The edited photograph should appear identical to the source photograph except for the hairstyle.

────────────────────────────────────
HEAD GEOMETRY
────────────────────────────────────

The skull is fixed.

The head is fixed.

The camera is fixed.

The pose is fixed.

The perspective is fixed.

The hairstyle must adapt to the existing head.

The head must never adapt to the hairstyle.

────────────────────────────────────
TERMINATION CONDITION
────────────────────────────────────

When the hairstyle has been successfully integrated into the existing photograph, terminate editing immediately.

Do not continue modifying facial anatomy.

Do not continue refining identity.

Do not continue improving realism outside the edited hair region.

Editing is complete once the requested hairstyle has been naturally integrated into the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GEOMETRY PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The supplied photograph is geometrically authoritative.

The photograph already contains the correct subject.

The photograph already contains the correct camera.

The photograph already contains the correct perspective.

The photograph already contains the correct framing.

The photograph already contains the correct composition.

This is a localized photographic editing task.

Only the requested hairstyle may change.

Every other geometric property of the photograph is immutable.

The final image must remain the exact same photograph with only the hairstyle edited.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GEOMETRY AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded photograph is the sole geometric authority.

Never improve geometry.

Never reconstruct geometry.

Never reinterpret geometry.

Never estimate better geometry.

Never generate a cleaner composition.

The hairstyle must conform to the existing photograph.

The photograph must never change to accommodate the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HEAD GEOMETRY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• skull dimensions

• skull proportions

• cranial contour

• forehead

• temples

• crown position

• occipital contour

• facial width

• facial height

• facial depth

• cheekbone position

• jawline

• chin

The anatomical structure is locked.

Only the visible hair may change.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HEAD POSITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The head is fixed.

Preserve exactly:

• image position

• horizontal position

• vertical position

• alignment

• translation

Do not:

• move the head

• shift the head

• recenter the head

• reposition the subject

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HEAD ROTATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the exact existing orientation.

Preserve:

• yaw

• pitch

• roll

The existing head angle is authoritative.

Do not:

• rotate

• straighten

• tilt

• lean

• nod

• twist

Even minimal rotational changes are prohibited.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACIAL LANDMARK COORDINATES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Every landmark must remain at the identical image coordinates.

Preserve:

• pupils

• eyelids

• eyebrows

• nose bridge

• nose tip

• nostrils

• philtrum

• lips

• mouth corners

• jawline

• chin

• ears

• hairline

No landmark may:

• translate

• rotate

• scale

• drift

• shift relative to the image borders.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUBJECT SCALE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The apparent size of the subject is locked.

Do not:

• enlarge the face

• shrink the face

• enlarge the head

• shrink the head

• increase portrait magnification

• reduce portrait magnification

The face must occupy exactly the same percentage of the image as the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
UPPER BODY ALIGNMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• neck position

• neck angle

• clavicles

• shoulders

• torso orientation

• body posture

The hairstyle adapts to the body.

The body never adapts to the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CAMERA LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The original camera is physically locked.

Preserve exactly:

• camera position

• camera height

• camera angle

• camera distance

• camera orientation

• viewpoint

• perspective

• focal length appearance

• lens compression

• viewing direction

Never move the virtual camera.

Never create a new viewpoint.

Never regenerate the portrait from another camera position.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FRAMING LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• framing

• crop

• zoom

• composition

• subject placement

• image boundaries

Do not:

• crop

• uncrop

• zoom

• zoom out

• extend canvas

• reposition subject

• recompose the portrait

The final image boundaries must be identical to the source photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PIXEL AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Outside the editable hair region, every existing pixel is authoritative.

Do not:

• regenerate

• redraw

• repaint

• reinterpret

• replace

• synthesize

non-hair pixels.

Only hairstyle pixels may be modified.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The edited image must appear to have been captured:

• by the same camera

• from the same position

• using the same lens

• at the same instant

• with identical framing

• with identical geometry

The hairstyle is the only permitted difference.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before completing the edit, mentally overlay the edited photograph on top of the source photograph.

Outside the edited hair region verify:

• identical head position

• identical head rotation

• identical facial scale

• identical facial landmark coordinates

• identical neck position

• identical shoulder position

• identical camera position

• identical camera distance

• identical perspective

• identical framing

• identical crop

• identical zoom

• identical composition

If any geometric mismatch exists outside the hairstyle, discard the edit and preserve the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STOP CONDITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Editing is complete only when:

• the requested hairstyle has been integrated

• head geometry is unchanged

• head position is unchanged

• head rotation is unchanged

• facial landmarks remain fixed

• facial scale is unchanged

• camera position is unchanged

• camera distance is unchanged

• zoom is unchanged

• framing is unchanged

• crop is unchanged

• composition is unchanged

• every non-hair pixel remains visually consistent with the source photograph

No further geometric modification is permitted.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The identity of the photographed subject is immutable.

The supplied person already exists in the source photograph.

This is a constrained photographic editing task.

This is NOT:

• portrait generation
• portrait recreation
• portrait synthesis
• identity generation
• face replacement
• face reconstruction

Only the requested hairstyle may be modified.

The photographed person must remain exactly the same individual.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded photograph is the sole authority for the subject's identity.

Every visible facial characteristic already exists.

Never estimate missing facial information.

Never infer better facial structure.

Never reconstruct facial anatomy.

Never replace the photographed person with a statistically similar face.

The existing face is already correct.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACE LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The face is a locked region.

Outside the editable hair region:

Do not regenerate facial pixels.

Do not redraw facial pixels.

Do not repaint facial pixels.

Do not reinterpret facial pixels.

Do not synthesize replacement facial pixels.

Preserve the existing photographed face exactly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACIAL STRUCTURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• skull
• forehead
• temples
• face width
• face height
• cheekbones
• jawline
• chin
• neck
• ears

Do not reshape anatomy.

Do not refine proportions.

Do not improve symmetry.

Do not alter facial dimensions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACIAL FEATURES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• eyes
• eyelids
• eyelashes
• eyebrows
• irises
• pupils
• nose
• nostrils
• lips
• mouth
• philtrum
• teeth

Every feature must remain identical.

Do not change:

• size
• shape
• angle
• spacing
• proportions
• orientation

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACIAL POSITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Every facial landmark must remain at the same image coordinates.

Do not reposition:

• eyes
• nose
• mouth
• ears
• chin

Do not move the face within the frame.

Do not shift facial alignment.

Do not create a new facial perspective.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKIN PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• pores
• skin texture
• fine lines
• wrinkles
• freckles
• moles
• birthmarks
• scars
• pigmentation
• blemishes
• natural asymmetry

These characteristics define the photographed individual.

Do not remove them.

Do not soften them.

Do not clean them.

Do not smooth them.

Do not replace them.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXPRESSION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• facial expression
• gaze direction
• eyelid openness
• eyebrow position
• mouth position
• lip tension

Do not create:

• a smile
• a neutral expression
• relaxed muscles
• stronger eye contact
• cosmetic expression improvements

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BEAUTIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The photographed appearance is already correct.

Do not beautify.

Do not retouch.

Do not cosmetically enhance.

Do not make the subject younger.

Do not make the subject healthier.

Do not make the subject thinner.

Do not make the subject more attractive.

Do not improve facial symmetry.

Do not improve skin quality.

Do not improve makeup.

Do not apply portrait enhancement.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The hairstyle must adapt to the photographed identity.

The photographed identity must never adapt to the hairstyle.

Hair is the editable element.

The face is not.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Compare the edited photograph against the source photograph.

Verify that:

• facial structure matches
• facial proportions match
• facial landmarks match
• skin texture matches
• pores match
• natural asymmetry matches
• expression matches
• gaze matches
• facial age matches
• facial attractiveness has not changed

If any facial characteristic differs, discard the modification and preserve the original face.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STOP CONDITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Editing is complete only when:

• the requested hairstyle has changed
• the photographed identity is unchanged
• facial pixels remain visually identical
• facial anatomy is unchanged
• skin is unchanged
• expression is unchanged
• no beautification has occurred

The only intentional visual difference between the source photograph and the final photograph is the requested hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POSE & CAMERA CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The supplied photograph is the only authoritative photograph.

The photographed subject already exists.

The photographed pose already exists.

The photographed camera already exists.

The photographed composition already exists.

This task is a localized photographic edit.

Only the requested hairstyle may change.

Everything else remains fixed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POSE AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The original pose is immutable.

The original body orientation is immutable.

The original head orientation is immutable.

The original camera viewpoint is immutable.

Never improve the pose.

Never normalize the pose.

Never beautify the pose.

Never generate a more flattering pose.

Never generate a more balanced pose.

The hairstyle must conform to the existing pose.

The pose must never change to accommodate the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HEAD ORIENTATION LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• head position

• head yaw

• head pitch

• head roll

• head tilt

• chin elevation

• chin projection

• neck angle

• facial direction

• eye direction

The existing orientation is authoritative.

Do not:

• rotate

• tilt

• straighten

• twist

• lean

• nod

• recenter

• reposition

The photographed head must remain rigidly fixed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BODY ORIENTATION LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• neck position

• neck rotation

• clavicles

• shoulders

• shoulder height

• shoulder rotation

• torso position

• torso orientation

• spine alignment

• body posture

The body is not editable.

The hairstyle adapts to the body.

The body never adapts to the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CAMERA LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The original camera is physically locked.

Preserve exactly:

• camera position

• camera height

• camera distance

• camera yaw

• camera pitch

• camera roll

• viewpoint

• perspective

• lens characteristics

• focal length appearance

• field of view

• subject scale

The camera must never move.

The portrait must never be regenerated from another viewpoint.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FRAMING LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve exactly:

• crop

• framing

• zoom

• composition

• subject placement

• image borders

Do not:

• crop

• uncrop

• zoom

• zoom out

• enlarge the subject

• shrink the subject

• move the subject

• recenter the subject

The edited photograph must occupy the identical image boundaries as the source photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE REGISTRATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Outside the editable hair region,
every visible structure must register perfectly with the original photograph.

If the original photograph and edited photograph are overlaid,
every non-hair structure must align exactly.

Preserve registration of:

• forehead

• eyebrows

• eyes

• eyelids

• nose

• lips

• chin

• ears

• neck

• shoulders

• clothing

• jewelry

• background

No measurable displacement is permitted.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PIXEL CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Outside the editable hair region,
the existing pixels are authoritative.

Do not regenerate them.

Do not repaint them.

Do not redraw them.

Do not reinterpret them.

Do not synthesize replacement pixels.

Reuse the existing photographed pixels whenever possible.

Only pixels belonging to the hairstyle may change.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCALIZED EDITING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The hairstyle is the editable object.

The face is not.

The neck is not.

The shoulders are not.

The body is not.

The camera is not.

The framing is not.

The composition is not.

The hairstyle must be integrated into the existing photograph.

The photograph must never be rebuilt around the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED CHANGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Do not:

• rotate the head

• tilt the head

• turn the face

• raise the chin

• lower the chin

• move the neck

• rotate the shoulders

• move the torso

• alter posture

• change gaze

• change facial direction

• change camera position

• change perspective

• change focal length

• change crop

• change zoom

• change subject scale

• change framing

• regenerate the portrait

• create another photograph

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONFLICT RESOLUTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

If any hairstyle instruction requires changing:

• pose

• anatomy

• framing

• camera

• perspective

• crop

• zoom

then the hairstyle instruction is incorrect.

Modify the hairstyle instead.

Never modify the photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before completing the edit,
compare the edited photograph directly against the source photograph.

Mentally overlay both images.

Outside the edited hair region verify:

• identical head position

• identical head rotation

• identical facial direction

• identical neck alignment

• identical shoulder alignment

• identical subject scale

• identical camera position

• identical camera distance

• identical perspective

• identical framing

• identical crop

• identical zoom

• identical composition

If any geometric difference exists outside the edited hair region,
discard the edit and preserve the source photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STOP CONDITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Editing is complete only when:

• the requested hairstyle has changed

• pose is unchanged

• body orientation is unchanged

• camera geometry is unchanged

• subject scale is unchanged

• framing is unchanged

• crop is unchanged

• zoom is unchanged

• every non-hair pixel remains visually consistent with the source photograph

The only intentional difference between the source photograph and the edited photograph is the requested hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CAMERA & COMPOSITION LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IMAGE CONTINUITY

The output is the identical source photograph after a professional haircut.

The photograph has not been retaken.

The camera has never moved.

The photographer has never moved.

The subject has never been repositioned.

Only the hairstyle has changed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CAMERA STATE

Preserve the original camera capture exactly.

Maintain:

• Camera position
• Camera height
• Camera distance
• Camera yaw
• Camera pitch
• Camera roll
• Camera orientation
• Camera perspective
• Camera focal length
• Lens characteristics
• Subject scale
• Framing
• Crop
• Composition

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE REGISTRATION

Outside the editable hair region, the edited photograph must register perfectly with the original photograph.

When the original and edited photographs are overlaid, every non-hair structure must occupy the identical pixel location.

Maintain perfect alignment of:

• Face
• Eyes
• Nose
• Mouth
• Jaw
• Chin
• Neck
• Shoulders
• Clothing
• Background
• Frame edges

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMMUTABLE COMPOSITION

Maintain exactly:

• Subject size within the frame
• Distance from head to frame edges
• Distance from shoulders to frame edges
• Background alignment
• Perspective
• Horizon
• Composition
• Negative space

No framing relationship may change.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED CAMERA CHANGES

Do not:

• Zoom
• Crop
• Expand the frame
• Change focal length
• Change perspective
• Change viewing distance
• Move the virtual camera
• Move the photographer
• Change subject scale
• Regenerate the image from another viewpoint

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION

Before completing the edit, compare the edited photograph with the original photograph.

Outside the editable hair region, every visible structure must align perfectly with the source photograph.

If any framing, perspective, scale, crop, camera position, or composition difference exists, correct only those differences while preserving the hairstyle.

The edit is complete only when the original and edited photographs differ exclusively within the editable hair region.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR COLOR PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The photographed hair colour is authoritative.

It already represents the subject's true appearance.

It must be preserved exactly unless the user explicitly requests a colour change.

The hairstyle may change.

The hair colour must not.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SOURCE AUTHORITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded photograph is the single source of truth for hair colour.

Do not estimate hair colour.

Do not infer hair colour.

Do not reinterpret hair colour.

Do not substitute hair colour.

Do not replace the photographed colour with a more attractive alternative.

Use only the colour information contained within the original photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COLOUR REPRODUCTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Reproduce the photographed hair colour exactly.

Preserve:

• overall colour

• root colour

• mid-length colour

• end colour

• highlights

• lowlights

• natural colour variation

• colour transitions

• colour depth

• colour density

Every colour relationship present in the original photograph must remain unchanged.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BRIGHTNESS PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the original brightness.

Do not brighten the hair.

Do not darken the hair.

Do not increase exposure.

Do not reduce exposure.

Do not increase luminance.

Do not decrease luminance.

Maintain the photographed tonal values exactly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COLOUR TEMPERATURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the original colour temperature.

Do not make the hair warmer.

Do not make the hair cooler.

Do not neutralize the colour.

Do not add golden tones.

Do not add copper tones.

Do not add red tones.

Do not add ash tones.

Do not add beige tones.

Do not remove naturally existing colour temperature.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SATURATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the photographed saturation.

Do not increase saturation.

Do not decrease saturation.

Do not enrich the colour.

Do not mute the colour.

Do not make the hair appear healthier by changing colour intensity.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NATURAL VARIATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Natural variation must remain identical.

Preserve:

• individual strand variation

• sun fading

• natural oxidation

• uneven pigmentation

• subtle colour shifts

• natural imperfections

Do not replace natural variation with uniform colour.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COLOUR CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

When synthesizing new strands required by the requested hairstyle:

Sample the colour from neighbouring original hair.

Continue existing colour patterns.

Continue existing highlight placement.

Continue existing lowlight placement.

Continue existing root depth.

New hair must appear to belong to the same photographed hair.

New strands must never introduce new colours.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORBIDDEN OPERATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The following operations are prohibited unless the user explicitly requests a colour change.

• Hair dye

• Colour correction

• Colour enhancement

• Colour balancing

• Colour grading

• Hair gloss

• Hair toning

• Blonde enhancement

• Brunette enhancement

• Root correction

• Highlight enhancement

• Lowlight enhancement

• Grey correction

• Colour normalization

• Colour beautification

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Compare the edited hair against the original photograph.

Verify that:

• overall colour matches

• roots match

• mid-lengths match

• ends match

• highlights match

• lowlights match

• brightness matches

• colour temperature matches

• saturation matches

• natural variation matches

If any colour difference exists that was not explicitly requested by the user, discard the colour modification and reproduce the photographed hair colour exactly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STOP CONDITION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Editing is complete only when:

• the requested hairstyle has been created

• the photographed hair colour has been preserved

• no unintended colour shift exists

• the edited hair appears to be the subject's original hair after a haircut rather than after a colour treatment

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LIGHTING PRESERVATION — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

Preserve the exact lighting conditions captured in the source photograph.

The hairstyle must integrate naturally into the existing lighting environment.

The lighting environment itself is immutable.

Only the hair may respond to the existing illumination.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMMUTABLE LIGHTING

Maintain exactly:

• Light direction
• Light intensity
• Light quality (hard or soft)
• Color temperature
• Exposure
• Brightness
• Contrast
• Dynamic range
• Highlight distribution
• Shadow direction
• Shadow intensity
• Ambient lighting
• White balance
• Black level

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR LIGHTING INTEGRATION

The edited hairstyle must inherit the lighting already present in the photograph.

Hair highlights, reflections, shadows and shading must be physically consistent with the existing illumination.

Do not create lighting that would require a different camera position or a different light source.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED LIGHTING CHANGES

Do not:

• Introduce new light sources
• Remove existing light sources
• Change exposure
• Change brightness
• Change contrast
• Change white balance
• Change colour temperature
• Change shadow direction
• Change highlight direction
• Change the overall mood of the photograph

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION

Compare the edited photograph with the source photograph.

Outside the editable hair region, lighting must remain visually identical.

Only newly generated hair may contain new highlights or shadows, and those must be fully explained by the original lighting conditions.

The edit is complete only when the photograph appears to have been captured under the identical lighting setup as the source image.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKIN PRESERVATION — ZERO TOLERANCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

Preserve the subject's skin exactly as captured in the source photograph.

This is a localized hair editing task.

It is not:

• Skin retouching
• Beauty enhancement
• Portrait enhancement
• Face enhancement
• Cosmetic editing
• Skin regeneration

Only the hairstyle may change.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMMUTABLE SKIN CHARACTERISTICS

Maintain exactly:

• Skin texture
• Skin colour
• Skin tone
• Skin reflectance
• Skin translucency
• Skin pores
• Fine lines
• Wrinkles
• Expression lines
• Freckles
• Moles
• Blemishes
• Acne marks
• Birthmarks
• Facial hair stubble
• Natural imperfections

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED SKIN MODIFICATIONS

Do not:

• Smooth the skin
• Beautify the skin
• Retouch the skin
• Airbrush the skin
• Remove pores
• Remove wrinkles
• Remove blemishes
• Remove freckles
• Remove moles
• Remove facial texture
• Change skin tone
• Change skin colour
• Change skin reflectance
• Add artificial skin detail
• Generate new skin

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TEXTURE CONTINUITY

Outside the editable hair region, preserve the original skin exactly.

The existing facial skin remains the authoritative reference.

New hair must blend naturally with the existing skin.

The existing skin must never be regenerated to accommodate the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION

Compare the edited photograph with the source photograph.

Outside the editable hair region, skin texture, pores, fine lines, colour and natural imperfections must remain visually identical.

The edit is complete only when the skin appears unchanged and only the hairstyle differs.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOREALISM & HAIR REALISM — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

The final image must be visually indistinguishable from an authentic, unedited photograph.

The hairstyle transformation must appear to have been performed in the real world before the original photograph was taken.

The viewer must perceive the result as the original photograph after a professional haircut, not as an AI-generated image.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC CONTINUITY

Preserve the photographic characteristics of the source photograph exactly.

Maintain:

• Camera sharpness
• Lens rendering
• Camera grain
• Image noise
• Fine detail
• Dynamic range
• Micro-contrast
• Optical realism
• Natural depth
• Edge fidelity

The generated hairstyle must inherit the photographic characteristics of the original image.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR REALISM

Generate physically plausible hair with realistic:

• Strand definition
• Strand flow
• Strand separation
• Hair density
• Volume distribution
• Root emergence
• Natural layering
• Edge transitions
• Flyaway hairs
• Hairline integration
• Strand thickness variation
• Natural strand irregularity

Hair must behave according to real-world hair physics.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SCALP & ROOT INTEGRATION

Hair must emerge naturally from the existing scalp.

Preserve realistic:

• Root density
• Root direction
• Growth pattern
• Scalp visibility
• Hairline transitions

There must be:

• No seams
• No halos
• No floating strands
• No cut-out appearance
• No wig effect
• No artificial blending

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED ARTIFACTS

Do not produce:

• CGI appearance
• Plastic hair
• Painted hair
• Airbrushed hair
• Synthetic texture
• Over-smoothed detail
• Artificial symmetry
• Repeating strand patterns
• Unrealistic density
• Unrealistic shine

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION

Compare the edited photograph with the original photograph.

The hairstyle must integrate seamlessly into the existing image.

Outside the editable hair region, the photograph must remain visually identical.

The completed edit must appear to be the original photograph captured immediately after the requested hairstyle was professionally created.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
UNIVERSAL NEGATIVE CONSTRAINTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PRIMARY OBJECTIVE

Perform only the explicitly requested transformation.

Every non-target region of the source photograph is immutable.

The uploaded photograph remains the authoritative reference.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRANSFORMATION SCOPE

Apply only the transformation defined by the active Style Block.

Ignore all competing hairstyle, beard, hair colour, portrait enhancement, beauty enhancement, or image generation priors.

Do not introduce any modification that was not explicitly requested.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED MODIFICATIONS

Do not:

• Regenerate the portrait
• Generate a different person
• Modify facial identity
• Modify facial geometry
• Modify skull geometry
• Modify pose
• Modify camera viewpoint
• Modify perspective
• Modify framing
• Modify crop
• Modify lighting
• Modify exposure
• Modify skin
• Modify clothing
• Modify accessories
• Modify background
• Modify composition

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROHIBITED ARTIFACTS

Do not generate:

• Halos
• Seams
• Floating hair
• Wig effect
• Clipping
• Ghosting
• Duplicate structures
• Distorted anatomy
• Broken hairlines
• Artificial symmetry
• Synthetic textures
• Incomplete blending

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONFLICT RESOLUTION

If any instruction conflicts with preserving the source photograph, preservation of the source photograph always takes priority.

Hair must adapt to the existing photograph.

The existing photograph must never be regenerated to accommodate the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION

Before completing the edit, compare the edited photograph with the original photograph.

Outside the editable hair region, every visible structure must remain unchanged.

Only the explicitly requested hairstyle transformation may differ.
`;
