/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/master-v3/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export const PROMPT_VERSION_V3 = "c43a4f30b93b";

export const MASTER_PROMPT_V3 = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDIT MODE — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is a localized photographic edit.

This is not image generation.

The uploaded photograph is authoritative.

The uploaded photograph is the final reference.

Do not generate a new photograph.

Do not recreate the photographed person.

Do not reinterpret the photographed person.

Do not reconstruct the photograph.

Edit the uploaded photograph.

Modify only the existing hairstyle.

Reuse the uploaded photograph everywhere else.

Everything outside the editable hair region must remain unchanged.

When uncertain:

Preserve the uploaded photograph.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Existing photograph edited

✓ Uploaded photograph preserved

✓ New photograph not generated

✓ Photographed person preserved

✓ Only hairstyle modified

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOCAL EDIT — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Edit only the photographed hair.

Do not edit the photograph.

Edit only the hairstyle.

Do not expand the edit beyond the hair.

Modify only the minimum pixels required.

Reuse the existing photograph everywhere else.

The edit must remain local.

The face is not editable.

The body is not editable.

The background is not editable.

Only the hairstyle is editable.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDITABLE REGION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Editable:

• hair

• roots

• strands

• parting

• length

• layering

• density

• texture

• scalp blending

Everything else is locked.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Edit remained local

✓ Only hairstyle changed

✓ No surrounding regions modified

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
GEOMETRY LOCK — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded head geometry is authoritative.

Reuse the uploaded head geometry exactly.

The head is a rigid object.

Do not move it.

Do not rotate it.

Do not tilt it.

Do not resize it.

Do not reposition it.

The skull is locked.

The jaw is locked.

The chin is locked.

The neck is locked.

The ears are locked.

Do not regenerate ears.

Head scale is locked.

Camera distance is locked.

Crop is locked.

Zoom is locked.

Framing is locked.

Perspective is locked.

Only surface hair may change.

Hair follows the existing head geometry.

Head geometry never adapts to the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Uploaded head geometry reused

✓ Head unchanged

✓ Skull unchanged

✓ Jaw unchanged

✓ Chin unchanged

✓ Ears unchanged

✓ Scale unchanged

✓ Crop unchanged

✓ Zoom unchanged

✓ Perspective unchanged

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY LOCK — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The photographed person already exists.

The uploaded face is authoritative.

The uploaded face is final.

Reuse the uploaded face exactly.

Do not create another person.

Do not create another version.

Do not recreate the person.

Do not reinterpret the person.

Do not improve the person.

Do not beautify the person.

Do not normalize the face.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FACE LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Face locked.

Eyes locked.

Eyebrows locked.

Nose locked.

Lips locked.

Jaw locked.

Chin locked.

Ears locked.

Neck locked.

Expression locked.

Gaze locked.

Facial structure locked.

Facial proportions locked.

Facial asymmetry locked.

Identity locked.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IDENTITY ANCHOR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded face already exists.

Reuse it exactly.

Do not redraw it.

Do not repaint it.

Do not regenerate it.

Do not replace it.

Do not synthesize new facial pixels.

The hairstyle adapts to the uploaded face.

The uploaded face never adapts to the hairstyle.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Uploaded face reused

✓ Same person

✓ Same face

✓ Same expression

✓ Same facial structure

✓ Same recognizability

✓ Identity preserved

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKIN LOCK — ABSOLUTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Skin locked.

Do not regenerate skin.

Do not repaint skin.

Do not smooth skin.

Do not beautify skin.

Do not retouch skin.

Preserve original skin exactly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRESERVE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve:

• pores

• texture

• wrinkles

• freckles

• blemishes

• scars

• birthmarks

• pigmentation

• natural imperfections

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORBIDDEN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

No beauty filter.

No skin smoothing.

No skin cleanup.

No skin enhancement.

No facial retouching.

No color contamination from hair.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Skin unchanged

✓ Pores unchanged

✓ Texture unchanged

✓ No beauty filter

✓ No skin regeneration

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CAMERA LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The uploaded camera is authoritative.

Reuse the uploaded camera exactly.

Camera locked.

Viewpoint locked.

Framing locked.

Crop locked.

Zoom locked.

Perspective locked.

Lens locked.

Camera distance locked.

Image scale locked.

Composition locked.

Do not create another camera.

Do not estimate another viewpoint.

Do not move the camera.

Do not zoom.

Do not crop.

Do not reframe.

Do not change perspective.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC CONTINUITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve:

• composition

• framing

• crop

• scale

• perspective

• camera position

• camera distance

• lens characteristics

• lens rendering

The output must match the uploaded photograph exactly.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Uploaded camera reused

✓ Camera unchanged

✓ Framing unchanged

✓ Crop unchanged

✓ Zoom unchanged

✓ Perspective unchanged

✓ Image scale unchanged

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR COLOR LOCK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Read the photographed hair color.

Read color only from the hair roots.

Ignore:

• background

• lighting

• clothing

• reflections

• environment

Do not estimate hair color.

Do not invent hair color.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COLOR REPRODUCTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve the photographed color.

Preserve:

• root color

• natural variation

• highlights

• lowlights

• color depth

Do not increase saturation.

Do not decrease saturation.

Do not warm the color.

Do not cool the color.

Do not brighten the color.

Do not darken the color.

Only change hair color when explicitly requested.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Root color preserved

✓ Natural variation preserved

✓ No color contamination

✓ No unintended color shift

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR EDIT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Edit the photographed hair.

Do not replace the photographed hair.

Modify the existing hairstyle.

Do not generate a new hairstyle.

Reuse the photographed hair wherever possible.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HAIR PRESERVATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve:

• root positions

• hairline

• natural density

• hair mass

• strand flow

• strand direction

• natural asymmetry

• flyaway hairs

• environmental movement

Preserve the photographed hairstyle until a requested style requires change.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STYLE TRANSFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Transform the existing hairstyle into the requested hairstyle.

The requested hairstyle must grow naturally from the photographed scalp.

Do not create a wig.

Do not create floating hair.

Do not create disconnected strands.

Blend naturally into the photographed hairline.

Only modify what the requested hairstyle requires.

Nothing else.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Existing hair modified

✓ Existing hair preserved where possible

✓ Hairline preserved

✓ Hair integrates naturally

✓ No wig appearance

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PHOTOGRAPHIC REALISM
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The final result must remain a real photograph.

Do not create an AI illustration.

Do not create CGI.

Do not create digital artwork.

Do not create synthetic textures.

Maintain photographic realism.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRESERVE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Preserve:

• lighting

• shadows

• highlights

• exposure

• white balance

• contrast

• image noise

• camera grain

• sharpness

• depth of field

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORBIDDEN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

No beauty filter.

No HDR effect.

No artificial sharpening.

No artificial blur.

No oversmoothing.

No duplicated hair strands.

No plastic skin.

No painted textures.

No AI artifacts.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SELF CHECK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Looks like a real photograph

✓ Lighting preserved

✓ Camera characteristics preserved

✓ No AI artifacts

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Before returning the edited photograph:

Verify every lock.

Verify every preserved region.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VERIFY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Local edit preserved

✓ Uploaded photograph preserved

✓ Same photographed person

✓ Same facial identity

✓ Same facial structure

✓ Same skin

✓ Same expression

✓ Same pose

✓ Same head geometry

✓ Same camera

✓ Same framing

✓ Same crop

✓ Same zoom

✓ Same perspective

✓ Same lighting

✓ Same background

✓ Hair color preserved unless instructed otherwise

✓ Requested hairstyle successfully applied

✓ Hair integrates naturally

✓ Result looks like a real photograph

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FAILURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

If any verification fails:

Discard the edit.

Restart from the uploaded photograph.

Do not return the failed result.

If any non-hair region has been regenerated:

Discard the edit immediately.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL RULE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Return the edited photograph only if:

• The hairstyle is the only edited region.

• Every non-hair pixel matches the uploaded photograph.

• The uploaded photograph has been preserved.

Otherwise:

Discard the edit.

Restart from the uploaded photograph.
`;
