import {
  PrismaClient,
  HairstyleCategory,
  GenderTarget,
  ServiceType,
} from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const hairstyles = [
    {
      slug: "bald",
      name: "Clean Bald",
      serviceType: ServiceType.BALD,
      category: null,
      description: "Clean shaved head.",
      thumbnailUrl: "/images/styles/bald.jpg",
      promptKey: "bald-clean-shaved",
      gender: GenderTarget.UNISEX,
      displayOrder: 1,
    },
    {
      slug: "buzz-cut",
      name: "0.0 mm Buzz Cut",
      serviceType: ServiceType.BUZZ_CUT,
      category: null,
      description: "Precision 0.0 mm buzz cut.",
      thumbnailUrl: "/images/styles/buzz-cut.jpg",
      promptKey: "0-0-mm-buzz-cut-zero-guard",
      gender: GenderTarget.UNISEX,
      displayOrder: 2,
    },
    {
      slug: "blunt-lob",
      name: "Blunt Lob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.LOB,
      description: "Polished blunt long bob.",
      thumbnailUrl: "/images/styles/blunt-lob.jpg",
      promptKey: "blunt-lob",
      gender: GenderTarget.FEMALE,
      displayOrder: 3,
    },
    {
      slug: "butterfly-cut",
      name: "Butterfly Cut",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.LAYERS,
      description: "Modern butterfly cut with cascading layers.",
      thumbnailUrl: "/images/styles/butterfly-cut.jpg",
      promptKey: "butterflycut",
      gender: GenderTarget.FEMALE,
      displayOrder: 4,
    },
    {
      slug: "french-bob",
      name: "French Bob with Bangs",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BOB,
      description: "Short Parisian-inspired bob with bangs.",
      thumbnailUrl: "/images/styles/french-bob.jpg",
      promptKey: "french-bob-with-bangs",
      gender: GenderTarget.FEMALE,
      displayOrder: 5,
    },
    {
      slug: "italian-bob",
      name: "Italian Bob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BOB,
      description: "Classic Italian bob.",
      thumbnailUrl: "/images/styles/italian-bob.jpg",
      promptKey: "italian-bob",
      gender: GenderTarget.FEMALE,
      displayOrder: 6,
    },
    {
      slug: "long-layers",
      name: "Long Layers",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.LAYERS,
      description: "Long, softly blended layers.",
      thumbnailUrl: null,
      promptKey: "long-layers",
      gender: GenderTarget.FEMALE,
      displayOrder: 7,
    },
    {
      slug: "mia-farrow-pixie",
      name: "Mia Farrow Pixie",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.PIXIE,
      description: "Short, refined Mia Farrow-inspired pixie.",
      thumbnailUrl: null,
      promptKey: "mia-farrow-pixie",
      gender: GenderTarget.FEMALE,
      displayOrder: 8,
    },
    {
      slug: "mid-length-layers",
      name: "Mid-Length Layers",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.LAYERS,
      description: "Mid-length haircut with soft layers.",
      thumbnailUrl: null,
      promptKey: "mid-length-layers",
      gender: GenderTarget.FEMALE,
      displayOrder: 9,
    },
    {
      slug: "old-money-bob",
      name: "Old Money Bob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BOB,
      description: "Polished, softly structured bob.",
      thumbnailUrl: null,
      promptKey: "old-money-bob",
      gender: GenderTarget.FEMALE,
      displayOrder: 10,
    },
    {
      slug: "parisian-gamine-pixie",
      name: "Parisian Gamine Pixie",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.PIXIE,
      description: "Chic Parisian gamine pixie.",
      thumbnailUrl: null,
      promptKey: "parisian-gamine-pixie",
      gender: GenderTarget.FEMALE,
      displayOrder: 11,
    },
    {
      slug: "pixie-side-fringe",
      name: "Pixie with Side Fringe",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.PIXIE,
      description: "Textured pixie with a soft side fringe.",
      thumbnailUrl: null,
      promptKey: "pixie-side-fringe",
      gender: GenderTarget.FEMALE,
      displayOrder: 12,
    },
    {
      slug: "side-parted-textured-bixie",
      name: "Side-Parted Textured Bixie",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BIXIE,
      description: "Textured bixie with a defined side part.",
      thumbnailUrl: null,
      promptKey: "side-parted-textured-bixie",
      gender: GenderTarget.FEMALE,
      displayOrder: 13,
    },
    {
      slug: "sleek-back-pixie",
      name: "Sleek-Back Pixie",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.PIXIE,
      description: "Sleek, swept-back pixie cut.",
      thumbnailUrl: null,
      promptKey: "sleek-back-pixie",
      gender: GenderTarget.FEMALE,
      displayOrder: 14,
    },
    {
      slug: "soft-curly-pixie",
      name: "Soft Curly Pixie",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.PIXIE,
      description: "Soft, curly pixie with natural texture.",
      thumbnailUrl: null,
      promptKey: "soft-curly-pixie",
      gender: GenderTarget.FEMALE,
      displayOrder: 15,
    },
    {
      slug: "soft-layered-bob",
      name: "Soft Layered Bob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BOB,
      description: "Soft bob with blended layers.",
      thumbnailUrl: null,
      promptKey: "soft-layered-bob",
      gender: GenderTarget.FEMALE,
      displayOrder: 16,
    },
    {
      slug: "soft-layered-french-bob",
      name: "Soft Layered French Bob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BOB,
      description: "French bob with soft layered movement.",
      thumbnailUrl: null,
      promptKey: "soft-layered-french-bob",
      gender: GenderTarget.FEMALE,
      displayOrder: 17,
    },
    {
      slug: "soft-lob",
      name: "Soft Lob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.LOB,
      description: "Soft long bob with natural movement.",
      thumbnailUrl: "/images/styles/soft-lob.jpg",
      promptKey: "soft-lob",
      gender: GenderTarget.FEMALE,
      displayOrder: 18,
    },
    {
      slug: "structured-blunt-bob",
      name: "Structured Blunt Bob",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.BOB,
      description: "Structured bob with a crisp blunt line.",
      thumbnailUrl: null,
      promptKey: "structured-blunt-bob",
      gender: GenderTarget.FEMALE,
      displayOrder: 19,
    },
    {
      slug: "undercut-pixie",
      name: "Undercut Pixie",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.PIXIE,
      description: "Pixie cut with a clean undercut.",
      thumbnailUrl: null,
      promptKey: "undercut-pixie",
      gender: GenderTarget.FEMALE,
      displayOrder: 20,
    },
    {
      slug: "wolf-cut",
      name: "Wolf Cut",
      serviceType: ServiceType.HAIRSTYLE,
      category: HairstyleCategory.WOLF,
      description: "Modern layered wolf cut.",
      thumbnailUrl: "/images/styles/wolf-cut.jpg",
      promptKey: "wolf-cut",
      gender: GenderTarget.FEMALE,
      displayOrder: 21,
    },
  ];

  for (const hairstyle of hairstyles) {
    await prisma.hairstyle.upsert({
      where: { slug: hairstyle.slug },
      update: hairstyle,
      create: hairstyle,
    });
  }

  console.log(`Seeded ${hairstyles.length} hairstyles.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
