import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const STYLE_ROOT = path.join(ROOT, "generation", "styles");
const OUTPUT_FILE = path.join(ROOT, "lib", "engine", "prompts", "styles.ts");

type StyleEntry = {
  id: string;
  name: string;
  prompt: string;
  source: string;
};

const PROMPT_KEY_BY_SOURCE_DIRECTORY: Record<string, string> = {
  bald: "bald-clean-shaved",
  "buzz-cut-0mm": "0-0-mm-buzz-cut-zero-guard",
};

const DISPLAY_NAMES: Record<string, string> = {
  "bald-clean-shaved": "Clean Bald",
  "blunt-lob": "Blunt Lob",
  butterflycut: "Butterfly Cut",
  "0-0-mm-buzz-cut-zero-guard": "0.0 mm Buzz Cut",
  "french-bob-with-bangs": "French Bob with Bangs",
  "italian-bob": "Italian Bob",
  "long-layers": "Long Layers",
  "mia-farrow-pixie": "Mia Farrow Pixie",
  "mid-length-layers": "Mid-Length Layers",
  "old-money-bob": "Old Money Bob",
  "parisian-gamine-pixie": "Parisian Gamine Pixie",
  "pixie-side-fringe": "Pixie with Side Fringe",
  "side-parted-textured-bixie": "Side-Parted Textured Bixie",
  "sleek-back-pixie": "Sleek-Back Pixie",
  "soft-curly-pixie": "Soft Curly Pixie",
  "soft-layered-bob": "Soft Layered Bob",
  "soft-layered-french-bob": "Soft Layered French Bob",
  "soft-lob": "Soft Lob",
  "structured-blunt-bob": "Structured Blunt Bob",
  "undercut-pixie": "Undercut Pixie",
  "wolf-cut": "Wolf Cut",
};

function slugify(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\s]+/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function titleFromSlug(slug: string): string {
  return slug
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function getStyleFile(styleDirectory: string): string | null {
  const versions = fs
    .readdirSync(styleDirectory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && /^v\d+$/i.test(entry.name))
    .map((entry) => entry.name)
    .sort((a, b) => Number(b.slice(1)) - Number(a.slice(1)));

  for (const version of versions) {
    const versionedFile = path.join(styleDirectory, version, "style.md");
    if (fs.existsSync(versionedFile)) return versionedFile;
  }

  const directFile = path.join(styleDirectory, "style.md");
  return fs.existsSync(directFile) ? directFile : null;
}

function readStyleEntries(): StyleEntry[] {
  if (!fs.existsSync(STYLE_ROOT)) {
    throw new Error(`Hairstyle directory not found:\n${STYLE_ROOT}`);
  }

  const entries: StyleEntry[] = [];

  for (const genderEntry of fs.readdirSync(STYLE_ROOT, { withFileTypes: true })) {
    if (!genderEntry.isDirectory()) continue;

    const genderDirectory = path.join(STYLE_ROOT, genderEntry.name);

    for (const styleEntry of fs.readdirSync(genderDirectory, { withFileTypes: true })) {
      if (!styleEntry.isDirectory()) continue;

      const styleFile = getStyleFile(path.join(genderDirectory, styleEntry.name));
      if (!styleFile) continue;

      const prompt = fs.readFileSync(styleFile, "utf8").trim();
      if (!prompt) throw new Error(`Style prompt is empty:\n${styleFile}`);

      const sourceId = slugify(styleEntry.name);
      const id = PROMPT_KEY_BY_SOURCE_DIRECTORY[sourceId] ?? sourceId;
      entries.push({
        id,
        name: DISPLAY_NAMES[id] ?? titleFromSlug(id),
        prompt,
        source: path.relative(ROOT, styleFile).replaceAll(path.sep, "/"),
      });
    }
  }

  return entries.sort((a, b) => a.id.localeCompare(b.id));
}

function buildPromptMap(entries: StyleEntry[]): Record<string, StyleEntry> {
  const map: Record<string, StyleEntry> = {};

  for (const entry of entries) {
    if (map[entry.id]) {
      throw new Error(`Duplicate production prompt key: ${entry.id}`);
    }

    map[entry.id] = entry;
  }

  return map;
}

function buildOutput(entries: StyleEntry[]): string {
  const ordered = Object.entries(buildPromptMap(entries)).sort(([a], [b]) => a.localeCompare(b));
  const records = ordered
    .map(
      ([key, entry]) =>
        `  ${JSON.stringify(key)}: {\n` +
        `    id: ${JSON.stringify(entry.id)},\n` +
        `    name: ${JSON.stringify(entry.name)},\n` +
        `    prompt: ${JSON.stringify(entry.prompt)},\n` +
        "  },",
    )
    .join("\n\n");

  const sourceComment = entries.length
    ? entries.map((entry) => ` * - ${entry.id}: ${entry.source}`).join("\n")
    : " * - No production style engines found.";

  return `/**\n * ============================================================\n * Draft My Hair\n * Compiled Hairstyle Prompt Library\n * ============================================================\n *\n * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.\n * Source directory: generation/styles/<gender>/<style>[/vX]/style.md\n * Generated by: npm run compile:prompts\n *\n * Production style sources:\n${sourceComment}\n */\n\nexport interface StylePrompt {\n  id: string;\n  name: string;\n  prompt: string;\n}\n\nexport const STYLE_PROMPTS: Record<string, StylePrompt> = {\n${records}\n};\n`;
}

const entries = readStyleEntries();
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, buildOutput(entries), "utf8");

console.log(`Compiled ${entries.length} production hairstyle engines.`);
console.log(`Output: ${path.relative(ROOT, OUTPUT_FILE)}`);
for (const entry of entries) {
  console.log(`- ${entry.id} <- ${entry.source}`);
}
