import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const PROMPT_FILE_PATTERN = /^\d{2}_.+\.md$/;

interface PromptSet {
  name: string;
  sourceDir: string;
  outputFile: string;
  exportName: string;
  versionName: string;
}

const PROMPT_SETS: PromptSet[] = [
  {
    name: "master",
    sourceDir: path.join(ROOT, "generation", "master"),
    outputFile: path.join(ROOT, "lib", "engine", "prompts", "master.ts"),
    exportName: "MASTER_PROMPT",
    versionName: "PROMPT_VERSION",
  },
  {
    name: "master-v2",
    sourceDir: path.join(ROOT, "generation", "master-v2"),
    outputFile: path.join(ROOT, "lib", "engine", "prompts", "master-v2.ts"),
    exportName: "MASTER_PROMPT_V2",
    versionName: "PROMPT_VERSION_V2",
  },
  {
    name: "master-v3",
    sourceDir: path.join(ROOT, "generation", "master-v3"),
    outputFile: path.join(ROOT, "lib", "engine", "prompts", "master-v3.ts"),
    exportName: "MASTER_PROMPT_V3",
    versionName: "PROMPT_VERSION_V3",
  },
  {
    name: "master-v3-single",
    sourceDir: path.join(ROOT, "generation", "master-v3-single"),
    outputFile: path.join(ROOT, "lib", "engine", "prompts", "master-v3-single.ts"),
    exportName: "MASTER_PROMPT_V3_SINGLE",
    versionName: "PROMPT_VERSION_V3_SINGLE",
  },
];

function getPromptFiles(sourceDir: string): string[] {
  if (!fs.existsSync(sourceDir)) {
    throw new Error(`Prompt directory not found:\n${sourceDir}`);
  }

  const files = fs
    .readdirSync(sourceDir)
    .filter((file) => PROMPT_FILE_PATTERN.test(file))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  if (files.length === 0) {
    throw new Error(`No prompt modules found in:\n${sourceDir}`);
  }

  return files;
}

function readPromptFiles(sourceDir: string, files: string[]): string {
  return files
    .map((file) => {
      const fullPath = path.join(sourceDir, file);
      const content = fs.readFileSync(fullPath, "utf8").trim();

      if (!content.length) {
        throw new Error(`Prompt file is empty:\n${fullPath}`);
      }

      return content;
    })
    .join("\n\n");
}

function escapeTemplateLiteral(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function generateVersion(prompt: string): string {
  return crypto.createHash("sha256").update(prompt).digest("hex").substring(0, 12);
}

function buildOutput(prompt: string, version: string, set: PromptSet): string {
  return `/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/${set.name}/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export const ${set.versionName} = "${version}";

export const ${set.exportName} = \`
${escapeTemplateLiteral(prompt)}
\`;
`;
}

function compileMasterPromptSets(): void {
  for (const set of PROMPT_SETS) {
    const prompt = readPromptFiles(set.sourceDir, getPromptFiles(set.sourceDir));
    const version = generateVersion(prompt);

    fs.mkdirSync(path.dirname(set.outputFile), { recursive: true });
    fs.writeFileSync(set.outputFile, buildOutput(prompt, version, set), "utf8");

    console.log(`${set.name.padEnd(16)} | Modules: ${getPromptFiles(set.sourceDir).length} | Version: ${version}`);
    console.log(`  Output: ${path.relative(ROOT, set.outputFile)}`);
    console.log("");
  }
}

function main(): void {
  console.log("");
  console.log("==========================================================");
  console.log("Draft My Hair Prompt Compiler");
  console.log("==========================================================");
  console.log("");

  compileMasterPromptSets();

  console.log("Prompt compilation completed successfully.");
  console.log("");
}

main();
