import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

const MASTER_DIR = path.join(ROOT, "generation", "master");

const OUTPUT_FILE = path.join(
  ROOT,
  "lib",
  "engine",
  "prompts",
  "master.ts"
);

// Only compile numbered prompt modules.
// README.md and other documentation files are ignored.
const FILE_PATTERN = /^\d{2}_.+\.md$/;

function getPromptFiles(): string[] {
  if (!fs.existsSync(MASTER_DIR)) {
    throw new Error(
      `Prompt directory not found:\n${MASTER_DIR}`
    );
  }

  const files = fs
    .readdirSync(MASTER_DIR)
    .filter((file) => FILE_PATTERN.test(file))
    .sort((a, b) =>
      a.localeCompare(b, undefined, {
        numeric: true,
      })
    );

  if (files.length === 0) {
    throw new Error(
      "No numbered prompt modules were found."
    );
  }

  return files;
}

function readPromptFiles(files: string[]): string {
  return files
    .map((file) => {
      const fullPath = path.join(
        MASTER_DIR,
        file
      );

      const content = fs
        .readFileSync(fullPath, "utf8")
        .trim();

      if (!content.length) {
        throw new Error(
          `Prompt file is empty:\n${file}`
        );
      }

      return `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MODULE: ${file}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${content}`;
    })
    .join("\n\n");
}

function escapeTemplateLiteral(
  text: string
): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function generateVersion(
  prompt: string
): string {
  return crypto
    .createHash("sha256")
    .update(prompt)
    .digest("hex")
    .substring(0, 12);
}

function buildOutput(
  prompt: string,
  version: string
): string {
  return `/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/master/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export const PROMPT_VERSION = "${version}";

export const MASTER_PROMPT = \`
${escapeTemplateLiteral(prompt)}
\`;
`;
}

function writeOutput(
  output: string
): void {
  fs.mkdirSync(
    path.dirname(OUTPUT_FILE),
    {
      recursive: true,
    }
  );

  fs.writeFileSync(
    OUTPUT_FILE,
    output,
    "utf8"
  );
}

function main(): void {
  console.log("");
  console.log(
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  );
  console.log(
    "Draft My Hair Prompt Compiler"
  );
  console.log(
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  );

  const files = getPromptFiles();

  const prompt = readPromptFiles(files);

  const version =
    generateVersion(prompt);

  const output = buildOutput(
    prompt,
    version
  );

  writeOutput(output);

  console.log("");

  console.log(
    `✓ Modules : ${files.length}`
  );

  console.log(
    `✓ Version : ${version}`
  );

  console.log(
    `✓ Output  : ${path.relative(
      ROOT,
      OUTPUT_FILE
    )}`
  );

  console.log("");
  console.log(
    "Prompt compilation completed successfully."
  );
  console.log("");
}

main();