import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

const PROMPT_FILE_PATTERN = /^\d{2}_.+\.md$/;
const STYLE_FILE_NAME = "style.md";

interface PromptSet {
  name: string;
  sourceDir: string;
  outputFile: string;
  exportName: string;
  versionName: string;
}

interface StylePromptSource {
  key: string;
  name: string;
  sourcePath: string;
  prompt: string;
}

const PROMPT_SETS: PromptSet[] = [
  {
    name: "master",
    sourceDir: path.join(ROOT, "generation", "master"),
    outputFile: path.join(
      ROOT,
      "lib",
      "engine",
      "prompts",
      "master.ts"
    ),
    exportName: "MASTER_PROMPT",
    versionName: "PROMPT_VERSION",
  },
  {
    name: "master-v2",
    sourceDir: path.join(ROOT, "generation", "master-v2"),
    outputFile: path.join(
      ROOT,
      "lib",
      "engine",
      "prompts",
      "master-v2.ts"
    ),
    exportName: "MASTER_PROMPT_V2",
    versionName: "PROMPT_VERSION_V2",
  },
  {
    name: "master-v3",
    sourceDir: path.join(ROOT, "generation", "master-v3"),
    outputFile: path.join(
      ROOT,
      "lib",
      "engine",
      "prompts",
      "master-v3.ts"
    ),
    exportName: "MASTER_PROMPT_V3",
    versionName: "PROMPT_VERSION_V3",
  },
  {
    name: "master-v3-single",
    sourceDir: path.join(ROOT, "generation", "master-v3-single"),
    outputFile: path.join(
      ROOT,
      "lib",
      "engine",
      "prompts",
      "master-v3-single.ts"
    ),
    exportName: "MASTER_PROMPT_V3_SINGLE",
    versionName: "PROMPT_VERSION_V3_SINGLE",
  },
];

const STYLES_SOURCE_DIR = path.join(
  ROOT,
  "generation",
  "styles"
);

const STYLES_OUTPUT_FILE = path.join(
  ROOT,
  "lib",
  "engine",
  "prompts",
  "styles.ts"
);

function getPromptFiles(sourceDir: string): string[] {
  if (!fs.existsSync(sourceDir)) {
    throw new Error(`Prompt directory not found:\n${sourceDir}`);
  }

  const files = fs
    .readdirSync(sourceDir)
    .filter((file) => PROMPT_FILE_PATTERN.test(file))
    .sort((a, b) =>
      a.localeCompare(b, undefined, {
        numeric: true,
      })
    );

  if (files.length === 0) {
    throw new Error(
      `No prompt modules found in:\n${sourceDir}`
    );
  }

  return files;
}

function readPromptFiles(
  sourceDir: string,
  files: string[]
): string {
  return files
    .map((file) => {
      const fullPath = path.join(sourceDir, file);

      const content = fs
        .readFileSync(fullPath, "utf8")
        .trim();

      if (!content.length) {
        throw new Error(
          `Prompt file is empty:\n${fullPath}`
        );
      }

      return content;
    })
    .join("\n\n");
}

function escapeTemplateLiteral(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function generateVersion(prompt: string): string {
  return crypto
    .createHash("sha256")
    .update(prompt)
    .digest("hex")
    .substring(0, 12);
}

function buildOutput(
  prompt: string,
  version: string,
  set: PromptSet
): string {
  return `/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/${set.name}/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export const ${set.versionName} = "${version}";

export const ${set.exportName} = \`
${escapeTemplateLiteral(prompt)}
\`;
`;
}

/* ============================================================
STYLE COMPILER
============================================================ */

function normalizeStyleKey(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/['’]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-")
    .toLowerCase();
}

function extractStyleName(content: string): string {
  const headingMatch = content.match(
    /^#\s+(.+?)\s*$/m
  );

  if (headingMatch?.[1]) {
    return headingMatch[1].trim();
  }

  const styleNameMatch = content.match(
    /^Style Name:\s*(.+?)\s*$/m
  );

  if (styleNameMatch?.[1]) {
    return styleNameMatch[1].trim();
  }

  throw new Error(
    `Unable to determine style name from style.md`
  );
}

function discoverStyleFiles(
  sourceDir: string
): string[] {
  if (!fs.existsSync(sourceDir)) {
    throw new Error(
      `Styles directory not found:\n${sourceDir}`
    );
  }

  const results: string[] = [];

  function walk(directory: string): void {
    const entries = fs.readdirSync(directory, {
      withFileTypes: true,
    });

    for (const entry of entries) {
      const fullPath = path.join(
        directory,
        entry.name
      );

      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }

      if (
        entry.isFile() &&
        entry.name === STYLE_FILE_NAME
      ) {
        results.push(fullPath);
      }
    }
  }

  walk(sourceDir);

  results.sort((a, b) =>
    a.localeCompare(b, undefined, {
      numeric: true,
    })
  );

  if (results.length === 0) {
    throw new Error(
      `No ${STYLE_FILE_NAME} files found in:\n${sourceDir}`
    );
  }

  return results;
}

function readStylePrompt(
  stylePath: string
): StylePromptSource {
  const prompt = fs
    .readFileSync(stylePath, "utf8")
    .trim();

  if (!prompt.length) {
    throw new Error(
      `Style prompt is empty:\n${stylePath}`
    );
  }

  const name = extractStyleName(prompt);
  const key = normalizeStyleKey(name);

  if (!key) {
    throw new Error(
      `Unable to create prompt key from style name:\n${name}\nSource: ${stylePath}`
    );
  }

  return {
    key,
    name,
    sourcePath: stylePath,
    prompt,
  };
}

function buildStylesOutput(
  styles: StylePromptSource[]
): string {
  const versionInput = styles
    .map((style) =>
      `${style.key}\n${style.prompt}`
    )
    .join("\n\n");

  const version = generateVersion(versionInput);

  const entries = styles
    .map((style) => {
      return `  ${JSON.stringify(style.key)}: {
    id: ${JSON.stringify(style.key)},
    name: ${JSON.stringify(style.name)},
    prompt: \`
${escapeTemplateLiteral(style.prompt)}
\`,
  },`;
    })
    .join("\n\n");

  return `/**
 * ============================================================
 * AUTO-GENERATED FILE
 * ============================================================
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * generation/styles/
 *
 * Generated by:
 * npm run compile:prompts
 *
 * ============================================================
 */

export interface StylePrompt {
  id: string;
  name: string;
  prompt: string;
}

export const STYLE_PROMPT_VERSION = "${version}";

export const STYLE_PROMPTS: Record<string, StylePrompt> = {
${entries}
};
`;
}

function compileStyles(): void {
  console.log("");
  console.log(
    "=========================================================="
  );
  console.log(
    "Draft My Hair Hairstyle Library Compiler"
  );
  console.log(
    "=========================================================="
  );
  console.log("");

  const styleFiles = discoverStyleFiles(
    STYLES_SOURCE_DIR
  );

  console.log(
    `Discovered ${styleFiles.length} hairstyle prompt files.`
  );
  console.log("");

  const styles = styleFiles.map(readStylePrompt);

  const seenKeys = new Map<string, string>();

  for (const style of styles) {
    const existing = seenKeys.get(style.key);

    if (existing) {
      throw new Error(
        [
          `Duplicate hairstyle prompt key detected: "${style.key}"`,
          `Existing source: ${existing}`,
          `Duplicate source: ${style.sourcePath}`,
          "",
          "Each hairstyle must have a unique canonical name.",
        ].join("\n")
      );
    }

    seenKeys.set(
      style.key,
      style.sourcePath
    );
  }

  styles.sort((a, b) =>
    a.key.localeCompare(b.key)
  );

  const output = buildStylesOutput(styles);

  fs.mkdirSync(
    path.dirname(STYLES_OUTPUT_FILE),
    {
      recursive: true,
    }
  );

  fs.writeFileSync(
    STYLES_OUTPUT_FILE,
    output,
    "utf8"
  );

  console.log(
    `✓ Styles compiled | Styles: ${styles.length}`
  );

  console.log(
    `  Output: ${path.relative(
      ROOT,
      STYLES_OUTPUT_FILE
    )}`
  );

  console.log("");

  for (const style of styles) {
    console.log(
      `  ✓ ${style.key.padEnd(32)} | ${style.name}`
    );
  }

  console.log("");
  console.log(
    "Hairstyle library compilation completed successfully."
  );
  console.log("");
}

/* ============================================================
MAIN
============================================================ */

function compileMasterPromptSets(): void {
  for (const set of PROMPT_SETS) {
    const files = getPromptFiles(
      set.sourceDir
    );

    const prompt = readPromptFiles(
      set.sourceDir,
      files
    );

    const version = generateVersion(prompt);

    const output = buildOutput(
      prompt,
      version,
      set
    );

    fs.mkdirSync(
      path.dirname(set.outputFile),
      {
        recursive: true,
      }
    );

    fs.writeFileSync(
      set.outputFile,
      output,
      "utf8"
    );

    console.log(
      `✓ ${set.name.padEnd(16)} | Modules: ${files.length} | Version: ${version}`
    );

    console.log(
      `  Output: ${path.relative(
        ROOT,
        set.outputFile
      )}`
    );

    console.log("");
  }
}

function main(): void {
  console.log("");
  console.log(
    "=========================================================="
  );
  console.log(
    "Draft My Hair Prompt Compiler"
  );
  console.log(
    "=========================================================="
  );
  console.log("");

  compileMasterPromptSets();

  compileStyles();

  console.log(
    "Prompt compilation completed successfully."
  );

  console.log("");
}

main();