ALTER TYPE "RnDTargetStatus" ADD VALUE IF NOT EXISTS 'HUMAN_REVIEW';
ALTER TYPE "RnDJobStatus" ADD VALUE IF NOT EXISTS 'HUMAN_REVIEW';
ALTER TYPE "RnDAttemptVerdict" ADD VALUE IF NOT EXISTS 'HUMAN_REVIEW';
ALTER TABLE "RnDAttempt" ADD COLUMN IF NOT EXISTS "adaptiveDecision" JSONB;
