CREATE TABLE "PromoCode" ("id" TEXT NOT NULL,"code" TEXT NOT NULL,"credits" INTEGER NOT NULL,"maxRedemptions" INTEGER,"redeemedCount" INTEGER NOT NULL DEFAULT 0,"startsAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PromoCode_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PromoRedemption" ("id" TEXT NOT NULL,"promoCodeId" TEXT NOT NULL,"userId" TEXT NOT NULL,"creditsGranted" INTEGER NOT NULL,"redeemedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromoRedemption_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PromoCode_code_key" ON "PromoCode"("code");
CREATE INDEX "PromoCode_isActive_idx" ON "PromoCode"("isActive");
CREATE INDEX "PromoCode_expiresAt_idx" ON "PromoCode"("expiresAt");
CREATE UNIQUE INDEX "PromoRedemption_promoCodeId_userId_key" ON "PromoRedemption"("promoCodeId","userId");
CREATE INDEX "PromoRedemption_userId_idx" ON "PromoRedemption"("userId");
CREATE INDEX "PromoRedemption_redeemedAt_idx" ON "PromoRedemption"("redeemedAt");
ALTER TABLE "PromoRedemption" ADD CONSTRAINT "PromoRedemption_promoCodeId_fkey" FOREIGN KEY ("promoCodeId") REFERENCES "PromoCode"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromoRedemption" ADD CONSTRAINT "PromoRedemption_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
